### ISSUE TITLE
Database column already created

### ISSUE THREAD

**Issue by FrankJeager** [Cloud9Developer/Jellyfin-Newsletter-Plugin#39]
There is some strange warnings in the log : 

[WARN] Error: SQLitePCL.pretty.SQLiteException: duplicate column name: Type
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, String& tail)
   at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Jellyfin.Plugin.Newsletters.Shared.DATA.SQLiteDatabase.ExecuteSQL(String query)
   at Jellyfin.Plugin.Newsletters.Shared.DATA.SQLiteDatabase.CreateTables(String[] tables)

**Comment by Cloud9Developer** [comment]
Yeah, that's expected. A version or 2 ago I needed to update the database columns, and put that check in to avoid disruptions for current users at the time.

WHEN i get around to releasing the next version, this will go away
