### ISSUE TITLE
Cannot send mail without username/password

### ISSUE THREAD

**Issue by skirmess** [Cloud9Developer/Jellyfin-Newsletter-Plugin#74]
I have a local mail relay in my home network which accepts mail on port 25 without authentication and forwards them to an outgoing SMTP server. Because of that I don't have to configure mail credentials on every system/in every app. Unfortunately, this plugin seems to not be able to send mails if the SMTP Username and SMTP Password field is left empty. When I press the Test button I see the following on my mail server.

```
postfix/smtpd: [mail.info] connect from jellyfin.example.net[192.168.0.3]
postfix/smtpd: [mail.info] lost connection after EHLO from jellyfin.example.net[192.168.0.3]
postfix/smtpd: [mail.info] disconnect from jellyfin.example.net[192.168.0.3] ehlo=1 commands=1
```

Looks like the plugin just gives up after saying hello.

```
220 mail.example.net ESMTP Postfix
EHLO jellyfin.example.net
250-mail.example.net
250-PIPELINING
250-SIZE 10240000
250-VRFY
250-ETRN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250-SMTPUTF8
250 CHUNKING
```

**Comment by Cloud9Developer** [comment]
What mail server do you use? I may try to set up an instance on my end and test it out (if setup is somewhat simple)

**Comment by Cloud9Developer** [comment]
Thanks for the info! Would you mind sharing some debug Newsletter logs as well?

**Comment by skirmess** [comment]
I never tried to get the plugin working. How would I do that? Just add something and wait 12 hours? Or is there a way to trigger that to debug it?

**Comment by skirmess** [comment]
Same error

```
May 17 18:50:48 mailhost postfix/smtpd[96]: connect from jellyfin.example.net[172.17.0.1]
May 17 18:50:48 mailhost postfix/smtpd[96]: lost connection after EHLO from jellyfin.example.net[172.17.0.1]
May 17 18:50:48 mailhost postfix/smtpd[96]: disconnect from jellyfin.example.net[172.17.0.1] ehlo=1 commands=1
```

**Comment by Cloud9Developer** [comment]
Can you share the newsletter logs? (jellyfin Dashboard > logs)

**Comment by skirmess** [comment]
I guess that's what you're looking for. ([full log](https://gist.github.com/skirmess/72db339f9edb12f105f982a649fef08f))
```
[NLP]: [2024-05-17] :: [20:49:07] - [INFO] Closing Database: /config/data/newsletters.db
[NLP]: [2024-05-17] :: [20:49:07] - [ERR] An error has occured: System.Net.Mail.SmtpException: Server does not support secure connections.
   at System.Net.Mail.SmtpConnection.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpTransport.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at Jellyfin.Plugin.Newsletters.Emails.EMAIL.Smtp.SendEmail()
[NLP]: [2024-05-17] :: [20:49:07] - [INFO] Database lock file does not exist. Database is not use: /config/data/newsletters.db.lock
```

**Comment by Cloud9Developer** [comment]
Yep! this is it! I'll use this info when working on the plugin to try and resolve/add this feature in! (since I believe it's designed currently to require username/password)

**Comment by solbu** [comment]
I don't use this plugin, but it came up as I was looking for email solutions for my jellyfin server.
But I have a comment that might be interesting none the less. :-)

I run jellyfin at home on actual hardware, no virtualization or containering like Docker.
I also run my actual official mailserver at home. Meaning that I don't have an email account with my ISP, Gmail, Hotmail, Yahoo or what they are all called.

So, internal systems can send email to the world using my internal Postfix mail system without any authentication. So if I was using this plugin, it would send email using no usernane, no password and no encryption _inside my local network_.

Many Linux users do this. They have an internal mail server on every system running linux, which feeds mail going to the outside world to another internal mailser which then sends it out using encryption and so on.

So this plugin should account for the fact that some users might want to use the mail server at _Localhost / 127.0.0.1_. It should not assume that all users of this plugin configure an outside server for facilitating email delivery.
