### ISSUE TITLE
Error when accessing the API docs

### ISSUE THREAD

**Issue by BLACK4585** [Cloud9Developer/Jellyfin-Newsletter-Plugin#87]
I get this error in the console when I try to access the Jellyfin API docs.
```
[12:11:20] [ERR] [68] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /api-docs/openapi.json.
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Ambiguous HTTP method for action - Jellyfin.Plugin.Newsletters.Emails.EMAIL.Smtp.NewsletterDbIsPopulated (Jellyfin.Plugin.Newsletters). Actions require an explicit HttpMethod binding for Swagger/OpenAPI 3.0
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Comment by Cloud9Developer** [comment]
Not sure this has anything to do with the Newsletter plugin?

**Comment by BLACK4585** [comment]
I strongly think so, since it mentions it in the error directly.
